# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/adamier/indie/IndieStudio

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/adamier/indie/IndieStudio

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/adamier/indie/IndieStudio/CMakeFiles /home/adamier/indie/IndieStudio/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/adamier/indie/IndieStudio/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named indie_studio

# Build rule for target.
indie_studio: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 indie_studio
.PHONY : indie_studio

# fast build rule for target.
indie_studio/fast:
	$(MAKE) -f CMakeFiles/indie_studio.dir/build.make CMakeFiles/indie_studio.dir/build
.PHONY : indie_studio/fast

src/Bomb.o: src/Bomb.cpp.o

.PHONY : src/Bomb.o

# target to build an object file
src/Bomb.cpp.o:
	$(MAKE) -f CMakeFiles/indie_studio.dir/build.make CMakeFiles/indie_studio.dir/src/Bomb.cpp.o
.PHONY : src/Bomb.cpp.o

src/Bomb.i: src/Bomb.cpp.i

.PHONY : src/Bomb.i

# target to preprocess a source file
src/Bomb.cpp.i:
	$(MAKE) -f CMakeFiles/indie_studio.dir/build.make CMakeFiles/indie_studio.dir/src/Bomb.cpp.i
.PHONY : src/Bomb.cpp.i

src/Bomb.s: src/Bomb.cpp.s

.PHONY : src/Bomb.s

# target to generate assembly for a file
src/Bomb.cpp.s:
	$(MAKE) -f CMakeFiles/indie_studio.dir/build.make CMakeFiles/indie_studio.dir/src/Bomb.cpp.s
.PHONY : src/Bomb.cpp.s

src/Bomberman.o: src/Bomberman.cpp.o

.PHONY : src/Bomberman.o

# target to build an object file
src/Bomberman.cpp.o:
	$(MAKE) -f CMakeFiles/indie_studio.dir/build.make CMakeFiles/indie_studio.dir/src/Bomberman.cpp.o
.PHONY : src/Bomberman.cpp.o

src/Bomberman.i: src/Bomberman.cpp.i

.PHONY : src/Bomberman.i

# target to preprocess a source file
src/Bomberman.cpp.i:
	$(MAKE) -f CMakeFiles/indie_studio.dir/build.make CMakeFiles/indie_studio.dir/src/Bomberman.cpp.i
.PHONY : src/Bomberman.cpp.i

src/Bomberman.s: src/Bomberman.cpp.s

.PHONY : src/Bomberman.s

# target to generate assembly for a file
src/Bomberman.cpp.s:
	$(MAKE) -f CMakeFiles/indie_studio.dir/build.make CMakeFiles/indie_studio.dir/src/Bomberman.cpp.s
.PHONY : src/Bomberman.cpp.s

src/Bomberman_run.o: src/Bomberman_run.cpp.o

.PHONY : src/Bomberman_run.o

# target to build an object file
src/Bomberman_run.cpp.o:
	$(MAKE) -f CMakeFiles/indie_studio.dir/build.make CMakeFiles/indie_studio.dir/src/Bomberman_run.cpp.o
.PHONY : src/Bomberman_run.cpp.o

src/Bomberman_run.i: src/Bomberman_run.cpp.i

.PHONY : src/Bomberman_run.i

# target to preprocess a source file
src/Bomberman_run.cpp.i:
	$(MAKE) -f CMakeFiles/indie_studio.dir/build.make CMakeFiles/indie_studio.dir/src/Bomberman_run.cpp.i
.PHONY : src/Bomberman_run.cpp.i

src/Bomberman_run.s: src/Bomberman_run.cpp.s

.PHONY : src/Bomberman_run.s

# target to generate assembly for a file
src/Bomberman_run.cpp.s:
	$(MAKE) -f CMakeFiles/indie_studio.dir/build.make CMakeFiles/indie_studio.dir/src/Bomberman_run.cpp.s
.PHONY : src/Bomberman_run.cpp.s

src/Debug.o: src/Debug.cpp.o

.PHONY : src/Debug.o

# target to build an object file
src/Debug.cpp.o:
	$(MAKE) -f CMakeFiles/indie_studio.dir/build.make CMakeFiles/indie_studio.dir/src/Debug.cpp.o
.PHONY : src/Debug.cpp.o

src/Debug.i: src/Debug.cpp.i

.PHONY : src/Debug.i

# target to preprocess a source file
src/Debug.cpp.i:
	$(MAKE) -f CMakeFiles/indie_studio.dir/build.make CMakeFiles/indie_studio.dir/src/Debug.cpp.i
.PHONY : src/Debug.cpp.i

src/Debug.s: src/Debug.cpp.s

.PHONY : src/Debug.s

# target to generate assembly for a file
src/Debug.cpp.s:
	$(MAKE) -f CMakeFiles/indie_studio.dir/build.make CMakeFiles/indie_studio.dir/src/Debug.cpp.s
.PHONY : src/Debug.cpp.s

src/EventListener.o: src/EventListener.cpp.o

.PHONY : src/EventListener.o

# target to build an object file
src/EventListener.cpp.o:
	$(MAKE) -f CMakeFiles/indie_studio.dir/build.make CMakeFiles/indie_studio.dir/src/EventListener.cpp.o
.PHONY : src/EventListener.cpp.o

src/EventListener.i: src/EventListener.cpp.i

.PHONY : src/EventListener.i

# target to preprocess a source file
src/EventListener.cpp.i:
	$(MAKE) -f CMakeFiles/indie_studio.dir/build.make CMakeFiles/indie_studio.dir/src/EventListener.cpp.i
.PHONY : src/EventListener.cpp.i

src/EventListener.s: src/EventListener.cpp.s

.PHONY : src/EventListener.s

# target to generate assembly for a file
src/EventListener.cpp.s:
	$(MAKE) -f CMakeFiles/indie_studio.dir/build.make CMakeFiles/indie_studio.dir/src/EventListener.cpp.s
.PHONY : src/EventListener.cpp.s

src/Exception.o: src/Exception.cpp.o

.PHONY : src/Exception.o

# target to build an object file
src/Exception.cpp.o:
	$(MAKE) -f CMakeFiles/indie_studio.dir/build.make CMakeFiles/indie_studio.dir/src/Exception.cpp.o
.PHONY : src/Exception.cpp.o

src/Exception.i: src/Exception.cpp.i

.PHONY : src/Exception.i

# target to preprocess a source file
src/Exception.cpp.i:
	$(MAKE) -f CMakeFiles/indie_studio.dir/build.make CMakeFiles/indie_studio.dir/src/Exception.cpp.i
.PHONY : src/Exception.cpp.i

src/Exception.s: src/Exception.cpp.s

.PHONY : src/Exception.s

# target to generate assembly for a file
src/Exception.cpp.s:
	$(MAKE) -f CMakeFiles/indie_studio.dir/build.make CMakeFiles/indie_studio.dir/src/Exception.cpp.s
.PHONY : src/Exception.cpp.s

src/Flame.o: src/Flame.cpp.o

.PHONY : src/Flame.o

# target to build an object file
src/Flame.cpp.o:
	$(MAKE) -f CMakeFiles/indie_studio.dir/build.make CMakeFiles/indie_studio.dir/src/Flame.cpp.o
.PHONY : src/Flame.cpp.o

src/Flame.i: src/Flame.cpp.i

.PHONY : src/Flame.i

# target to preprocess a source file
src/Flame.cpp.i:
	$(MAKE) -f CMakeFiles/indie_studio.dir/build.make CMakeFiles/indie_studio.dir/src/Flame.cpp.i
.PHONY : src/Flame.cpp.i

src/Flame.s: src/Flame.cpp.s

.PHONY : src/Flame.s

# target to generate assembly for a file
src/Flame.cpp.s:
	$(MAKE) -f CMakeFiles/indie_studio.dir/build.make CMakeFiles/indie_studio.dir/src/Flame.cpp.s
.PHONY : src/Flame.cpp.s

src/GameGUI.o: src/GameGUI.cpp.o

.PHONY : src/GameGUI.o

# target to build an object file
src/GameGUI.cpp.o:
	$(MAKE) -f CMakeFiles/indie_studio.dir/build.make CMakeFiles/indie_studio.dir/src/GameGUI.cpp.o
.PHONY : src/GameGUI.cpp.o

src/GameGUI.i: src/GameGUI.cpp.i

.PHONY : src/GameGUI.i

# target to preprocess a source file
src/GameGUI.cpp.i:
	$(MAKE) -f CMakeFiles/indie_studio.dir/build.make CMakeFiles/indie_studio.dir/src/GameGUI.cpp.i
.PHONY : src/GameGUI.cpp.i

src/GameGUI.s: src/GameGUI.cpp.s

.PHONY : src/GameGUI.s

# target to generate assembly for a file
src/GameGUI.cpp.s:
	$(MAKE) -f CMakeFiles/indie_studio.dir/build.make CMakeFiles/indie_studio.dir/src/GameGUI.cpp.s
.PHONY : src/GameGUI.cpp.s

src/IGUI.o: src/IGUI.cpp.o

.PHONY : src/IGUI.o

# target to build an object file
src/IGUI.cpp.o:
	$(MAKE) -f CMakeFiles/indie_studio.dir/build.make CMakeFiles/indie_studio.dir/src/IGUI.cpp.o
.PHONY : src/IGUI.cpp.o

src/IGUI.i: src/IGUI.cpp.i

.PHONY : src/IGUI.i

# target to preprocess a source file
src/IGUI.cpp.i:
	$(MAKE) -f CMakeFiles/indie_studio.dir/build.make CMakeFiles/indie_studio.dir/src/IGUI.cpp.i
.PHONY : src/IGUI.cpp.i

src/IGUI.s: src/IGUI.cpp.s

.PHONY : src/IGUI.s

# target to generate assembly for a file
src/IGUI.cpp.s:
	$(MAKE) -f CMakeFiles/indie_studio.dir/build.make CMakeFiles/indie_studio.dir/src/IGUI.cpp.s
.PHONY : src/IGUI.cpp.s

src/Map.o: src/Map.cpp.o

.PHONY : src/Map.o

# target to build an object file
src/Map.cpp.o:
	$(MAKE) -f CMakeFiles/indie_studio.dir/build.make CMakeFiles/indie_studio.dir/src/Map.cpp.o
.PHONY : src/Map.cpp.o

src/Map.i: src/Map.cpp.i

.PHONY : src/Map.i

# target to preprocess a source file
src/Map.cpp.i:
	$(MAKE) -f CMakeFiles/indie_studio.dir/build.make CMakeFiles/indie_studio.dir/src/Map.cpp.i
.PHONY : src/Map.cpp.i

src/Map.s: src/Map.cpp.s

.PHONY : src/Map.s

# target to generate assembly for a file
src/Map.cpp.s:
	$(MAKE) -f CMakeFiles/indie_studio.dir/build.make CMakeFiles/indie_studio.dir/src/Map.cpp.s
.PHONY : src/Map.cpp.s

src/Menu.o: src/Menu.cpp.o

.PHONY : src/Menu.o

# target to build an object file
src/Menu.cpp.o:
	$(MAKE) -f CMakeFiles/indie_studio.dir/build.make CMakeFiles/indie_studio.dir/src/Menu.cpp.o
.PHONY : src/Menu.cpp.o

src/Menu.i: src/Menu.cpp.i

.PHONY : src/Menu.i

# target to preprocess a source file
src/Menu.cpp.i:
	$(MAKE) -f CMakeFiles/indie_studio.dir/build.make CMakeFiles/indie_studio.dir/src/Menu.cpp.i
.PHONY : src/Menu.cpp.i

src/Menu.s: src/Menu.cpp.s

.PHONY : src/Menu.s

# target to generate assembly for a file
src/Menu.cpp.s:
	$(MAKE) -f CMakeFiles/indie_studio.dir/build.make CMakeFiles/indie_studio.dir/src/Menu.cpp.s
.PHONY : src/Menu.cpp.s

src/Option.o: src/Option.cpp.o

.PHONY : src/Option.o

# target to build an object file
src/Option.cpp.o:
	$(MAKE) -f CMakeFiles/indie_studio.dir/build.make CMakeFiles/indie_studio.dir/src/Option.cpp.o
.PHONY : src/Option.cpp.o

src/Option.i: src/Option.cpp.i

.PHONY : src/Option.i

# target to preprocess a source file
src/Option.cpp.i:
	$(MAKE) -f CMakeFiles/indie_studio.dir/build.make CMakeFiles/indie_studio.dir/src/Option.cpp.i
.PHONY : src/Option.cpp.i

src/Option.s: src/Option.cpp.s

.PHONY : src/Option.s

# target to generate assembly for a file
src/Option.cpp.s:
	$(MAKE) -f CMakeFiles/indie_studio.dir/build.make CMakeFiles/indie_studio.dir/src/Option.cpp.s
.PHONY : src/Option.cpp.s

src/Player.o: src/Player.cpp.o

.PHONY : src/Player.o

# target to build an object file
src/Player.cpp.o:
	$(MAKE) -f CMakeFiles/indie_studio.dir/build.make CMakeFiles/indie_studio.dir/src/Player.cpp.o
.PHONY : src/Player.cpp.o

src/Player.i: src/Player.cpp.i

.PHONY : src/Player.i

# target to preprocess a source file
src/Player.cpp.i:
	$(MAKE) -f CMakeFiles/indie_studio.dir/build.make CMakeFiles/indie_studio.dir/src/Player.cpp.i
.PHONY : src/Player.cpp.i

src/Player.s: src/Player.cpp.s

.PHONY : src/Player.s

# target to generate assembly for a file
src/Player.cpp.s:
	$(MAKE) -f CMakeFiles/indie_studio.dir/build.make CMakeFiles/indie_studio.dir/src/Player.cpp.s
.PHONY : src/Player.cpp.s

src/Renderer.o: src/Renderer.cpp.o

.PHONY : src/Renderer.o

# target to build an object file
src/Renderer.cpp.o:
	$(MAKE) -f CMakeFiles/indie_studio.dir/build.make CMakeFiles/indie_studio.dir/src/Renderer.cpp.o
.PHONY : src/Renderer.cpp.o

src/Renderer.i: src/Renderer.cpp.i

.PHONY : src/Renderer.i

# target to preprocess a source file
src/Renderer.cpp.i:
	$(MAKE) -f CMakeFiles/indie_studio.dir/build.make CMakeFiles/indie_studio.dir/src/Renderer.cpp.i
.PHONY : src/Renderer.cpp.i

src/Renderer.s: src/Renderer.cpp.s

.PHONY : src/Renderer.s

# target to generate assembly for a file
src/Renderer.cpp.s:
	$(MAKE) -f CMakeFiles/indie_studio.dir/build.make CMakeFiles/indie_studio.dir/src/Renderer.cpp.s
.PHONY : src/Renderer.cpp.s

src/SceneManager.o: src/SceneManager.cpp.o

.PHONY : src/SceneManager.o

# target to build an object file
src/SceneManager.cpp.o:
	$(MAKE) -f CMakeFiles/indie_studio.dir/build.make CMakeFiles/indie_studio.dir/src/SceneManager.cpp.o
.PHONY : src/SceneManager.cpp.o

src/SceneManager.i: src/SceneManager.cpp.i

.PHONY : src/SceneManager.i

# target to preprocess a source file
src/SceneManager.cpp.i:
	$(MAKE) -f CMakeFiles/indie_studio.dir/build.make CMakeFiles/indie_studio.dir/src/SceneManager.cpp.i
.PHONY : src/SceneManager.cpp.i

src/SceneManager.s: src/SceneManager.cpp.s

.PHONY : src/SceneManager.s

# target to generate assembly for a file
src/SceneManager.cpp.s:
	$(MAKE) -f CMakeFiles/indie_studio.dir/build.make CMakeFiles/indie_studio.dir/src/SceneManager.cpp.s
.PHONY : src/SceneManager.cpp.s

src/Splash.o: src/Splash.cpp.o

.PHONY : src/Splash.o

# target to build an object file
src/Splash.cpp.o:
	$(MAKE) -f CMakeFiles/indie_studio.dir/build.make CMakeFiles/indie_studio.dir/src/Splash.cpp.o
.PHONY : src/Splash.cpp.o

src/Splash.i: src/Splash.cpp.i

.PHONY : src/Splash.i

# target to preprocess a source file
src/Splash.cpp.i:
	$(MAKE) -f CMakeFiles/indie_studio.dir/build.make CMakeFiles/indie_studio.dir/src/Splash.cpp.i
.PHONY : src/Splash.cpp.i

src/Splash.s: src/Splash.cpp.s

.PHONY : src/Splash.s

# target to generate assembly for a file
src/Splash.cpp.s:
	$(MAKE) -f CMakeFiles/indie_studio.dir/build.make CMakeFiles/indie_studio.dir/src/Splash.cpp.s
.PHONY : src/Splash.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/indie_studio.dir/build.make CMakeFiles/indie_studio.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/indie_studio.dir/build.make CMakeFiles/indie_studio.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/indie_studio.dir/build.make CMakeFiles/indie_studio.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... indie_studio"
	@echo "... edit_cache"
	@echo "... src/Bomb.o"
	@echo "... src/Bomb.i"
	@echo "... src/Bomb.s"
	@echo "... src/Bomberman.o"
	@echo "... src/Bomberman.i"
	@echo "... src/Bomberman.s"
	@echo "... src/Bomberman_run.o"
	@echo "... src/Bomberman_run.i"
	@echo "... src/Bomberman_run.s"
	@echo "... src/Debug.o"
	@echo "... src/Debug.i"
	@echo "... src/Debug.s"
	@echo "... src/EventListener.o"
	@echo "... src/EventListener.i"
	@echo "... src/EventListener.s"
	@echo "... src/Exception.o"
	@echo "... src/Exception.i"
	@echo "... src/Exception.s"
	@echo "... src/Flame.o"
	@echo "... src/Flame.i"
	@echo "... src/Flame.s"
	@echo "... src/GameGUI.o"
	@echo "... src/GameGUI.i"
	@echo "... src/GameGUI.s"
	@echo "... src/IGUI.o"
	@echo "... src/IGUI.i"
	@echo "... src/IGUI.s"
	@echo "... src/Map.o"
	@echo "... src/Map.i"
	@echo "... src/Map.s"
	@echo "... src/Menu.o"
	@echo "... src/Menu.i"
	@echo "... src/Menu.s"
	@echo "... src/Option.o"
	@echo "... src/Option.i"
	@echo "... src/Option.s"
	@echo "... src/Player.o"
	@echo "... src/Player.i"
	@echo "... src/Player.s"
	@echo "... src/Renderer.o"
	@echo "... src/Renderer.i"
	@echo "... src/Renderer.s"
	@echo "... src/SceneManager.o"
	@echo "... src/SceneManager.i"
	@echo "... src/SceneManager.s"
	@echo "... src/Splash.o"
	@echo "... src/Splash.i"
	@echo "... src/Splash.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

